(add-to-list 'feature-mode-hook (lambda ()
                                  (whitespace-mode t)
                                  (compile-on-save-mode)
                                  )
             )
